### ISSUE TITLE
Running dstat2graphs on Docker container

### ISSUE THREAD

**Issue by kotsachin** [sh2/dstat2graphs#2]
Hello,

I am using dstat2graphs to plot statistics taken by command 'dstat -tvfn --output log.csv 1'.
But on my machine docker is running. i have use docker on host machine. Because of docker some additional columns gets added because of temporary Ethernet port created by Docker.

When i tried to plot using command line or GUI option it gives following error:

```
 Invalid DS name at /home/sachin/pgbench-tools/dstat2graphs/dstat2graphs.pl line 290. 
```

Please tell me solution to avoid above problem.

**Comment by sh2** [comment]
Can you give me the dstat log file which causes such a error ?

**Comment by kotsachin** [comment]
Yes. Sure.

Please check below Gist link for dstat.csv file.
In below file you can find extra ethernet port created by docker ("net/veth1759ce4",,"net/veth187386f",,"net/veth65546e0").

https://gist.github.com/kotsachin/359d957fa9fd097144fe

Thanks.

**Comment by sh2** [comment]
Thank you.
I fixed it. Please see 62cc524

**Comment by kotsachin** [comment]
Thanks for instant fix!!!
